# syntax=docker/dockerfile:1
# check=error=true
FROM nixos/nix AS dev

# copy over everything (excl. ``.dockerignore``)
WORKDIR /app
COPY . .
# if copying files from windows: remove carriage returns from shell scripts
RUN tr -d '\r' < ./run.sh 1<> ./run.sh

# check that everything is where we expect it to be
RUN ls | grep server;
RUN ls | grep client;
# test connection to nix-cache
RUN curl https://cache.nixos.org/nix-cache-info; 

SHELL ["/root/.nix-profile/bin/nix-shell", "--command"]

# a heredoc would look nicer, but debugging it is harder.
# setup
RUN head -c 1000 /dev/null > hmac.bin;
RUN echo 'HMAC_KEY_PATH="../hmac.bin"' > .env;
RUN rustup default stable;

# precompile dependencies
RUN cd /app/client && npm install;
RUN cd /app/server && cargo build --bin web;

VOLUME /app/server/data
VOLUME /app/server/src
VOLUME /app/client/src
CMD ["/root/.nix-profile/bin/nix-shell", "--run", "./run.sh"]
